export const EDIT_INPUT_TITLE = 'EDIT_INPUT_TITLE';
export const EDIT_INPUT_CATEGORY = 'EDIT_INPUT_CATEGORY';
export const EDIT_LOADING = 'EDIT_LOADING';
export const EDIT_THUMBNAIL_URL = 'EDIT_THUMBNAIL_URL';
export const EDIT_SUMMARY = 'EDIT_SUMMARY';
export const LOGIN_STATE = 'LOGIN_STATE';
